---
stages:
  - docker
  - post

include:
  - project: devops/pipes
    file: /templates/v2/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/update-docker-hub-readme.gitlab-ci.yml

variables:
  RESTIC_VERSION: 0.15.1
  DOCKER_IMAGE_NAME: cenk1cenk2/restic-backup
  DOCKERFILE_CONTEXT: .
  DOCKER_IMAGE_BUILD_ARGS: RESTIC_VERSION={{ .RESTIC_VERSION }}
  DOCKER_IMAGE_TAGS: latest,{{ .RESTIC_VERSION }}
  README_DESCRIPTION: |
    Restic backup server forked from the original.

build-docker-image:
  extends: .docker-build-dockerhub
  stage: docker
  only:
    refs:
      - schedules
      - master
      - tags

update-docker-hub-readme:
  only:
    refs:
      - master
      - tags
